### ISSUE TITLE
HTTP 500 Error when logging in with steam (install with new binary)

### ISSUE THREAD

**Issue by PaddyGameTV** [jetelain/cTab#60]
```
Mai 05 16:41:38 Ctab ctab[6280]: info: AspNet.Security.OpenId.Steam.SteamAuthenticationHandler[4]
Mai 05 16:41:38 Ctab ctab[6280]:       Error from RemoteAuthentication: The authentication response was rejected because the anti-forgery token was invalid..
Mai 05 16:41:38 Ctab ctab[6280]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Mai 05 16:41:38 Ctab ctab[6280]:       Connection id "0HN3D25F1AOGK", Request id "0HN3D25F1AOGK:00000009": An unhandled exception was thrown by the application.
Mai 05 16:41:38 Ctab ctab[6280]:       Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
Mai 05 16:41:38 Ctab ctab[6280]:        ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: The authentication response was rejected because the anti-forgery token was invalid.
Mai 05 16:41:38 Ctab ctab[6280]:          --- End of inner exception stack trace ---
Mai 05 16:41:38 Ctab ctab[6280]:          at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
Mai 05 16:41:38 Ctab ctab[6280]:          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mai 05 16:41:38 Ctab ctab[6280]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jetelain** [comment]
Https is required by Chrome, cerbot can setup https for you : https://certbot.eff.org/

**Comment by PaddyGameTV** [comment]
no, at the moment it only runs on http
and yes the steam api token is in the json file

**Comment by PaddyGameTV** [comment]
> Https is required by Chrome, cerbot can setup https for you : https://certbot.eff.org/

certbot is now running and the certificat is created

what is the next step to run the ctab on https?

**Comment by jetelain** [comment]
It should works if the application is accessed via https. If not, can you send me the application URL ?
You can contact me on Discord : https://discord.gg/JPQJAbpW57
